// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Notification struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Title     sql.NullString `json:"title"`
	Message   sql.NullString `json:"message"`
	Read      sql.NullBool   `json:"read"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Task struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    string         `json:"category"`
	Priority    string         `json:"priority"`
	Deadline    sql.NullTime   `json:"deadline"`
}

type TaskTimeLog struct {
	ID        int32         `json:"id"`
	TaskID    sql.NullInt32 `json:"task_id"`
	StartTime sql.NullTime  `json:"start_time"`
	EndTime   sql.NullTime  `json:"end_time"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type User struct {
	ID             int32     `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
