// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Task struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	Priority    sql.NullString `json:"priority"`
	Deadline    sql.NullTime   `json:"deadline"`
}

type User struct {
	ID             int32          `json:"id"`
	Email          sql.NullString `json:"email"`
	HashedPassword sql.NullString `json:"hashed_password"`
}
