// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, title, message)
VALUES ($1, $2, $3)
    RETURNING user_id
`

type CreateNotificationParams struct {
	UserID  sql.NullInt32  `json:"user_id"`
	Title   sql.NullString `json:"title"`
	Message sql.NullString `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, createNotification, arg.UserID, arg.Title, arg.Message)
	var user_id sql.NullInt32
	err := row.Scan(&user_id)
	return user_id, err
}
