// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, name, description, category, priority, deadline)
VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, user_id, name, description, category, priority, deadline
`

type CreateTaskParams struct {
	UserID      int32          `json:"user_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	Priority    sql.NullString `json:"priority"`
	Deadline    sql.NullTime   `json:"deadline"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Priority,
		arg.Deadline,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Deadline,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, name, description, category, priority, deadline
FROM tasks
WHERE user_id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, userID int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, userID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Deadline,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, name, description, category, priority, deadline
FROM tasks
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Priority,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
